using UnityEngine;

namespace GoblinRTS.Economy
{
    public class IncomeTicker : MonoBehaviour
    {
        public static IncomeTicker Instance { get; private set; }

        [SerializeField] private float tickIntervalSeconds = 2f;
        public float TickIntervalSeconds => tickIntervalSeconds;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Debug.LogWarning("[Economy] Duplicate IncomeTicker detected. Destroying duplicate.");
                Destroy(gameObject);
                return;
            }

            Instance = this;
        }

        private void Start()
        {
            Debug.Log("[Economy] IncomeTicker active as shared tick source only. Income is generated by Fortress buildings.");
        }

        private void OnDestroy()
        {
            if (Instance == this)
            {
                Instance = null;
            }
        }
    }
}